version: "2"

networks:
  kim_message_pipeline_net:
    driver: bridge

services:
  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: "kafdrop"
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"
    depends_on:
      - "kafka"
    networks: 
      - kim_message_pipeline_net


  kafka:
    image: obsidiandynamics/kafka
    container_name: "kafka"
    restart: "no"
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
    networks: 
      - kim_message_pipeline_net